name: Docker Build, Push & Deploy

on:
  release:
    types: [published]
  push:
    branches: ['main']

jobs:
  build:
    uses: atb-as/workflows/.github/workflows/cluster-docker-build-tag-push.yaml@v2
    with:
      image: gcr.io/atb-mobility-platform/jwt-decode
      dockerfile: _docker/Dockerfile
      deploy: false
    secrets:
      github_pat: ${{ secrets.GH_PAT }}
