name: Build and push
on:
  push:
    branches: 
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/939812594010/locations/global/workloadIdentityPools/ci-builds/providers/github'
          service_account: 'sa-gh-gcr-writer@atb-mobility-platform-staging.iam.gserviceaccount.com'
      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="gcr.io/atb-mobility-platform/jwt-decode"
          echo ::set-output name=latest_image::${IMAGE}:latest
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Configure docker for GCR
        uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Build images
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./_docker/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tagged_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
