name: Build and push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sun') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: go mod download
      - run: go get -u golang.org/x/lint/golint
      - run: ./_tools/test.sh
      - run: ./_tools/bench.sh
      - run: mkdir -p _build/bin
      - run: GO111MODULE=on CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -o ./_build/bin/main ./cmd/main.go
      - uses: elgohr/Publish-Docker-Github-Action@master
        if: github.ref == 'refs/heads/master'
        with:
          name: simonschneider/traefik-jwt-decode
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.version.outputs.tag }}"
          workdir: _build
